# base image
FROM golang:1.18.1 AS builder
# set up work directory
WORKDIR /app
# copy files and build app
COPY . .
RUN CGO_ENABLED=0 go build -o /go/bin/app .


# final stage using scratch image as base
FROM scratch
COPY --from=builder /go/bin/app /app
ENTRYPOINT [ "/app" ]
